org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Minecraft and NeoForge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.255
neo_version_range=[21.1.255,21.2)
loader_version_range=[4,)
java_version=21

# Mod information
mod_id=elytratrails
mod_name=Aki Elytra Trails Reforged
mod_version=1.4.9-neoforge.3
mod_group_id=io.github.achilleus1
mod_archive_name=aki-elytra-trails-reforged
mod_license=MPL-2.0
mod_authors=Achilleus (Achilleus-1)
