modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Achilleus-1/Aki-ElytraTrails-Reforged/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://linktr.ee/achilleus_"
authors="${mod_authors}"
credits="Ported from Elytra Contrails by dbrighthd."
logoFile="assets/achilleus/achilleus-logo-white.png"
description='''Product of Achilleus.
https://linktr.ee/achilleus_

Elytra trails, presets, wingtip settings, twirls, and optional arrow and allay trails. Created and maintained by Achilleus for NeoForge 1.21.1.'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cloth_config"
type="optional"
versionRange="[15.0.140,)"
ordering="AFTER"
side="CLIENT"

[[mixins]]
config="elytratrails.client.mixins.json"
